Villanova_Dev1/src/objects/Campaign_Form_Item__c.object
<CustomObject>
    <description>Used to store items to be included in Campaign Event registration forms.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Campaign_Form_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Form Item</label>
    <nameField>
        <label>Campaign Form Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Form Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Villanova_Dev1/src/objects/Campaign_Form_Item_Picklist__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Form_Item__c</fullName>
        <label>Campaign Form Item</label>
        <referenceTo>Campaign_Form_Item__c</referenceTo>
        <relationshipLabel>Campaign Form Item Picklists</relationshipLabel>
        <relationshipName>Campaign_Form_Item_Picklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Form Item Picklist</label>
    <nameField>
        <label>Picklist Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Form Item Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Villanova_Dev1/src/classes/ctrlDynamicField.cls
public class ctrlDynamicField {
    public String strDefaultValue { get;set; }
    public String strField {get;set;}
    public Map<String, Schema.SObjectField> FieldMap;
    public String[] lstPick {get;set;}
    public String strCamp {get;set;}
    //public List<Campaign_Form_Item_Picklist__c> lstCFFs = new List<Campaign_Form_Item_Picklist__c>();
    
    public ctrlDynamicField(){       
    }
    
    public List<SelectOption> getSelectOpts(){
        List<SelectOption> options = new List<SelectOption>(); 
        List<Campaign_Form_Item_Picklist__c> lstCFFs = [Select Id, Name, Campaign_Form_Item__r.Name 
            from Campaign_Form_Item_Picklist__c where Campaign_Form_Item__r.Campaign__c =: strCamp];
        if (lstCFFs.size() > 0){
            for (Campaign_Form_Item_Picklist__c p : lstCFFs){
                if (p.Campaign_Form_Item__r.Name == strField){
                    options.add(new SelectOption(p.Name, p.Name));
                }
            }
        } else {
            //Backup to support forms built before picklist add field changes made 
            //(This method limits forms to 10 picklists or less)
            FieldMap = Schema.SObjectType.Lead.fields.getMap();
            SObjectField f;
            Schema.DescribeFieldResult d;
            
            f = FieldMap.get(strField);
            if (f != null){
                d = f.getDescribe();
                List<Schema.PicklistEntry> ple = d.getPicklistValues();
            
               for( Schema.PicklistEntry p : ple)
               {
                  options.add(new SelectOption(p.getLabel(), p.getValue()));
               }  
            }
            
        }
             
        return options; 
    }
    
    static testMethod void testMethods() {
        ctrlDynamicField ctrl = new ctrlDynamicField();
        ctrl.strField = 'Industry';
        ctrl.getSelectOpts();
    }
}