Villanova_Dev1/src/objects/VEM_Event__c.object
<CustomObject>
    <description>List of Villanova University planned events</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <picklist>
            <controllingField>Time_Interval__c</controllingField>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:15 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <inlineHelpText>Enter up to 255 characters</inlineHelpText>
        <label>Event Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <referenceTo>VEM_Location__c</referenceTo>
        <relationshipName>Event_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Notes__c</fullName>
        <inlineHelpText>Enter up to 32,768 characters</inlineHelpText>
        <label>Event Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Sponsor__c</fullName>
        <inlineHelpText>Enter the sponsor/group for this event</inlineHelpText>
        <label>Event Sponsor</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Athletic Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletic Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakfast - Buffet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakfast - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinic / Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinner - Buffet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinner - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exhibit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund Raiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intramurals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luncheon - Buffet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luncheon - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting w/Snacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outside Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Volume__c</fullName>
        <inlineHelpText>Enter the number of people expected at this event</inlineHelpText>
        <label>Expected Attendance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Approver__c</fullName>
        <label>Location Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Location_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_By_Time__c</fullName>
        <label>Ready By Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurrence_Type__c</fullName>
        <label>Recurrence Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sponsor_Account__c</fullName>
        <label>Sponsor Account</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Email__c</fullName>
        <label>Sponsor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sponsor_Phone__c</fullName>
        <label>Sponsor Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <controllingField>Time_Interval__c</controllingField>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:15 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Villanova_Dev1/src/classes/VEM_EventController.cls
public with sharing class VEM_EventController
{

    ////////////////////////////////////////////////////////////////////
    // Dates Formatted in Eastern Standard Time (not the default GST) //
    ////////////////////////////////////////////////////////////////////

    public String todayString      { get { return todayPlus(0); } }
    public String todayPlus0String { get { return todayPlus(0); } }
    public String todayPlus1String { get { return todayPlus(1); } }
    public String todayPlus2String { get { return todayPlus(2); } }
    public String todayPlus3String { get { return todayPlus(3); } }
    public String todayPlus4String { get { return todayPlus(4); } }
    public String todayPlus5String { get { return todayPlus(5); } }
    public String todayPlus6String { get { return todayPlus(6); } }

    private String todayPlus(Integer days)
    {
        //return System.now().format('EEEE - MMMM d, yyyy h:mm a (z)');
        //return System.now().format('EEEE - MMMM d, yyyy h:mm a (z)', 'EDT');
        //return System.now().format('EEEE - MMMM d, yyyy h:mm a (z)', 'EST');
        return System.now().addDays(days).format('EEEE, MMMM d, yyyy');
    }

    ////////////////////////////////////
    // Today's Connelly Center Events //
    ////////////////////////////////////

    private static final String CONNELLY_CENTER = 'Connelly Center';
         
    public List<VEM_Event__c> eventsInConnellyToday
    {
        get
        {
            //ToDo: Look for better way to find all locations with Connelly Center as parent, grandparent, etc.
            return  [  SELECT Id, Name, Start_Time__c, End_Time__c, Event_Location__r.Name, Event_Type__c, Event_Sponsor__c
                         FROM VEM_Event__c
                        WHERE Start_Date__c = TODAY
                          AND Event_Status__c = 'Approved'
                          AND (Event_Location__r.Name = :CONNELLY_CENTER
                           OR  Event_Location__r.Parent_Location__r.Name = :CONNELLY_CENTER
                           OR  Event_Location__r.Parent_Location__r.Parent_Location__r.Name = :CONNELLY_CENTER)
                     ORDER BY Start_Date_Time__c, End_Date_Time__c, Name];
        }
    }

    public List<VEM_Event__c> getEventsInConnellyToday()
    {
        return eventsInConnellyToday;
    }

    /////////////////////////////
    // Today's Athletic Events //
    /////////////////////////////

	private final Profile athleticsApproverProfile = [ SELECT Id, Name FROM Profile WHERE Name = 'VEM Athletics User' LIMIT 1];

    private List<VEM_Event__c> m_eventsInAthleticsToday;
    public List<VEM_Event__c> eventsInAthleticsToday
    {
        get
        {
            if (m_eventsInAthleticsToday == null)
            {
                m_eventsInAthleticsToday =
                        [  SELECT Id, Name, Start_Time__c, End_Time__c, Event_Location__r.Name, Event_Type__c, Event_Sponsor__c
                                 FROM VEM_Event__c
                                WHERE Start_Date__c = TODAY
                                  AND Event_Status__c = 'Approved'
                                  AND Location_Approver__r.Profile.Id = :athleticsApproverProfile.Id
                         ORDER BY Start_Date_Time__c, End_Date_Time__c, Name];
            }
            return m_eventsInAthleticsToday;
        }
    }

    public List<VEM_Event__c> getEventsInAthleticsToday()
    {
        return eventsInAthleticsToday;
    }

    public void ClearCacheOfEventsInAthleticsToday()
    {
        m_eventsInAthleticsToday = null;
    }

    /////////////////////////////////
    // This Week's Athletic Events //
    /////////////////////////////////

    private List<VEM_Event__c> m_eventsInAthleticsThisWeek;
    public List<VEM_Event__c> eventsInAthleticsThisWeek
    {
        get
        {
            if (m_eventsInAthleticsThisWeek == null)
            {
                m_eventsInAthleticsThisWeek =
                        [  SELECT Id, Name, Start_Date__c, Start_Time__c, End_Date__c, End_Time__c, Event_Location__r.Name, Event_Type__c, Event_Sponsor__c
                                 FROM VEM_Event__c
                                WHERE (Start_Date__c >= TODAY
                                  AND  Start_Date__c <= NEXT_N_DAYS:6)
                                  AND Event_Status__c = 'Approved'
                                  AND Location_Approver__r.Profile.Id = :athleticsApproverProfile.Id
                         ORDER BY Start_Date_Time__c, End_Date_Time__c, Name];
            }
            return m_eventsInAthleticsThisWeek;
        }
    }

    public List<VEM_Event__c> getEventsInAthleticsThisWeek()
    {
        return eventsInAthleticsThisWeek;
    }

    public List<VEM_Event__c> eventsInAthleticsTodayPlus0 { get { return getEventsInAthleticsTodayPlus(0); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus1 { get { return getEventsInAthleticsTodayPlus(1); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus2 { get { return getEventsInAthleticsTodayPlus(2); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus3 { get { return getEventsInAthleticsTodayPlus(3); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus4 { get { return getEventsInAthleticsTodayPlus(4); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus5 { get { return getEventsInAthleticsTodayPlus(5); } }
    public List<VEM_Event__c> eventsInAthleticsTodayPlus6 { get { return getEventsInAthleticsTodayPlus(6); } }

	private List<VEM_Event__c> getEventsInAthleticsTodayPlus(Integer days)
	{
		Date dateFilter = Date.today().addDays(days);
		List<VEM_Event__c> filteredList = new List<VEM_Event__c>();

		for (VEM_Event__c event : eventsInAthleticsThisWeek)
		{
			if (event.Start_Date__c == dateFilter)
			{
				filteredList.add(event);
			}
		} 

		return filteredList;
	}

    public void ClearCacheOfEventsInAthleticsThisWeek()
    {
        m_eventsInAthleticsThisWeek = null;
    }

    /////////////////////////////////
    // Connelly Operations Reports //
    /////////////////////////////////

	private final Profile connellyCenterApproverProfile = [ SELECT Id, Name FROM Profile WHERE Name = 'VEM Connelly Center User' LIMIT 1];

	private Date m_connellyOperationsReportDate = defaultOperationsReportDate();
	public Date connellyOperationsReportDate
	{
		get { return m_connellyOperationsReportDate; }
		set { m_connellyOperationsReportDate = value; }
	}

	private Date m_connellyProjectionStartDate = defaultProjectionStartDate();
	public Date connellyProjectionStartDate
	{
		get { return m_connellyProjectionStartDate; }
		set { m_connellyProjectionStartDate = value; }
	}

	private Date m_connellyProjectionEndDate = defaultProjectionEndDate();
	public Date connellyProjectionEndDate
	{
		get { return m_connellyProjectionEndDate; }
		set { m_connellyProjectionEndDate = value; }
	}

	private Date defaultOperationsReportDate()
	{
		Date reportDate = Date.today();

		//try
		//{
			//Check URL parameter first (format: yyyy-mm-dd)
			String reportDateStr = ApexPages.currentPage().getParameters().get('date');
			if (reportDateStr != null)
			{
				reportDate = Date.valueOf(reportDateStr);
			}
		//}
		//catch (Exception ex)
		//{
		//	//Ignore error
		//}

		return reportDate;
	}

    private Date defaultProjectionStartDate()
    {
    	Date startDate = Date.today();

		//Check URL parameters first (format: yyyy-mm-dd)
		String startDateStr = ApexPages.currentPage().getParameters().get('start');
		if (startDateStr != null)
		{
			startDate = Date.valueOf(startDateStr);
		}

        return startDate;
    }

    private Date defaultProjectionEndDate()
    {
        //Date endDate =  connellyProjectionStartDate.addDays(14).toStartOfWeek().addDays(-1);
        Date endDate = connellyProjectionStartDate.addDays(13);

		//Check URL parameters first (format: yyyy-mm-dd)
		String endDateStr = ApexPages.currentPage().getParameters().get('end');
		if (endDateStr != null)
		{
			Date tempEndDate = Date.valueOf(endDateStr);
			if (tempEndDate >= connellyProjectionStartDate)
			{
				endDate = tempEndDate;
			}
		}

        return endDate;
    }

    public String operationsReportDateString
    {
        get
        {
            return Datetime.newInstance(connellyOperationsReportDate.year(), connellyOperationsReportDate.month(), connellyOperationsReportDate.day()).format('EEEE, MMMM d, yyyy');
        }
    }

    public String projectionDateRangeString
    {
        get
        {
            //format('MMM d, yyyy');
            return connellyProjectionStartDate.format() + ' - ' + connellyProjectionEndDate.format();
        }
    }

    private List<VEM_Event__c> m_connellyOperationsReportEvents;
    public List<VEM_Event__c> connellyOperationsReportEvents
    {
        get
        {
            if (m_connellyOperationsReportEvents == null)
            {
                m_connellyOperationsReportEvents = getConnellyOperationsEvents(connellyOperationsReportDate, connellyOperationsReportDate);
            }
            return m_connellyOperationsReportEvents;
        }
    }

    private List<VEM_Event__c> m_connellyOperationsProjectionEvents;
    public List<VEM_Event__c> connellyOperationsProjectionEvents
    {
        get
        {
            if (m_connellyOperationsProjectionEvents == null)
            {
                m_connellyOperationsProjectionEvents = getConnellyOperationsEvents(connellyProjectionStartDate, connellyProjectionEndDate);
            }
            return m_connellyOperationsProjectionEvents;
        }
    }

    private List<VEM_Event__c> getConnellyOperationsEvents(Date startDate, Date endDate)
    {
        return [  SELECT Id, Name, Event_Type__c, Event_Location__r.Name,
                         Ready_By_Time__c,
                         Start_Date__c, Start_Time__c, Start_Date_Time__c,
                         End_Date__c, End_Time__c, End_Date_Time__c,
                         Event_Sponsor__c, Sponsor_Account__c, Sponsor_Phone__c, Sponsor_Email__c,
                         Expected_Volume__c, Event_Description__c, Event_Notes__c, Recurrence_Type__c
                    FROM VEM_Event__c
                   WHERE Start_Date__c >= :startDate
                     AND End_Date__c <= :endDate
                     AND Event_Status__c = 'Approved'
                     AND Location_Approver__r.Profile.Id = :connellyCenterApproverProfile.Id
                ORDER BY Start_Date_Time__c, End_Date_Time__c, Name ];
    }

}